services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.dev.Dockerfile
    image: afs-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    networks:
      - afs-net

  backend:
    build:
      context: .
      dockerfile: docker/backend.dev.Dockerfile
    image: afs-backend-dev
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    networks:
      - afs-net

networks:
  afs-net:
    driver: bridge
