version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: afs-frontend
    image: afs-frontend-prod
    ports:
      - "5173:5173"
    restart: unless-stopped
    env_file:
      - client/.env.production
    networks:
      - afs-net

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: afs-backend
    image: afs-backend-prod
    ports:
      - "5000:5000"
    restart: unless-stopped
    env_file:
      - server/.env.production
    depends_on:
      - frontend
    networks:
      - afs-net

networks:
  afs-net:
    driver: bridge
